baseurl: "https://www.brianthicks.com/"
languageCode: "en-us"
title: "Brian Hicks"
theme: "2018"
# Posts per page
paginate: 5
sectionPagesMenu: "main"

permalinks:
  post: "/post/:year/:month/:day/:slug"

# Theme Params
params:
  author:
    name: "Brian Hicks"
    email: brian@brianthicks.com
  description: "Developing in St. Louis"
  gravatar: "fca2f8814a85e23af81f5553adbd4d62"

  # To add a header background to the main site, save your image under static/img/.
  # If now image path is provided, a orange background will be shown instead.
  # headerText: ""
  headerImage: ""

  copyright: "The content on this site is licensed as <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC Attribution-ShareAlike</a> except for code samples, which are licensed as <a rel=\"license\" href=\"http://creativecommons.org/publicdomain/zero/1.0/\">CC0</a>."

  social:
    twitter: brianhicks
