baseurl: "https://www.brianthicks.com/"
languageCode: "en-us"
title: "Brian Hicks"
theme: "type"
# Add your tracking code to enable Google Analytics
googleAnalytics: ""
# Posts per page
paginate: 5

permalinks:
  post: "/post/:year/:month/:day/:slug"

params:
  author: "Brian Hicks"
  description: "Developing in St. Louis"
  gravatar: "fca2f8814a85e23af81f5553adbd4d62"

  # headerText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
  # To add a header background to the main site, save your image under static/img/.
  # If now image path is provided, a orange background will be shown instead.
  headerImage: ""
  copyright: "The content on this site is licensed as <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nd/4.0/\">CC Attribution-NoDerivatives</a> except for code samples, which are licensed as <a rel=\"license\" href=\"http://creativecommons.org/publicdomain/zero/1.0/\">CC0</a>."

  segment:
    write_key: ki2miw1o3b

  social:
  # Insert your accout name and the icon will be shown in the right menu
    rss: true
    email: "brian@brianthicks.com"
    github: "BrianHicks"
    twitter: "brianhicks"
    behance: ""
    bitbucket: ""
    dribbble: ""
    facebook: ""
    flickr: ""
    googleplus: ""
    instagram: ""
    linkedin: ""
    pinterest: ""
    reddit: ""
    soundcloud: ""
    stackexchange: ""
    steam: ""
    tumblr: ""
    wordpress: ""
    youtube: ""
